server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true

auth:
  jwt:
    issuer: dis-auth
    expires-min: 120
    secret: "change-this-in-prod-very-long-secret-key-1234567890"
