server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authdb
    username: auth
    password: auth
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info

auth:
  jwt:
    issuer: dis-auth
    expires-min: 120
    secret: "change-this-in-prod-very-long-secret-key-1234567890"
