spring:
  application:
    name: gateway

  # (privremeno) skroz isključi security na gateway-u dok testiraš rute
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
      - org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: auth-service-direct
          uri: http://localhost:8086
          predicates:
            - Path=/auth-service/**
          filters:
            - RewritePath=/auth-service/?(?<remaining>.*), /${remaining}

        - id: catalog-service-direct
          uri: http://localhost:8082
          predicates:
            - Path=/catalog-service/**
          filters:
            - RewritePath=/catalog-service/?(?<remaining>.*), /${remaining}

        - id: orders-service-direct
          uri: http://localhost:8083
          predicates:
            - Path=/orders-service/**
          filters:
            - RewritePath=/orders-service/?(?<remaining>.*), /${remaining}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,env
  endpoint:
    gateway:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

auth:
  jwt:
    issuer: dis-auth
    secret: "change-this-in-prod-very-long-secret-key-1234567890"
