spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ordersdb
    username: orders
    password: orders
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
server:
  port: 8083
