spring:
  application:
    name: payments-service
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsdb
    username: payments
    password: payments
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true

server:
  port: 8084
