services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: dis-rabbit
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI http://localhost:15672 (guest/guest)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
